apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: customermanagementapi
  namespace: pitstop
spec:
  host: customermanagementapi
  subsets:
    - name: v1
      labels:
        version: "1.0"
    - name: v2
      labels:
        version: "2.0"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customermanagementapi
  namespace: pitstop
spec:
  hosts:
    - customermanagementapi
  http:
    - route:
      - destination:
          host: customermanagementapi
          subset: v1
        weight: 75
      - destination:
          host: customermanagementapi
          subset: v2
        weight: 25
