apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: timeservice
    version: "1.0"
  name: timeservice
  namespace: pitstop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: timeservice
        version: "1.0"
    spec:
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        image: pitstop/timeservice:1.0
        imagePullPolicy: IfNotPresent
        name: timeservice
      restartPolicy: Always
