apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: webapp
    version: "1.0"
  name: webapp
  namespace: pitstop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: webapp
        version: "1.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: pitstop/webapp:1.0
        imagePullPolicy: IfNotPresent
        name: webapp
        ports:
        - containerPort: 7000
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: webapp
    version: "1.0"
  name: webapp
  namespace: pitstop
spec:
  type: LoadBalancer
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  selector:
    system: pitstop
    app: webapp
    version: "1.0"

