apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: workshopmanagementapi
    version: v1
  name: workshopmanagementapi
  namespace: pitstop
spec:
  replicas: 2
  template:
    metadata:
      labels:
        system: pitstop
        app: workshopmanagementapi
        version: v1
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ApplicationInsights__InstrumentationKey
          value: befe2a5c-f406-4e9c-9a77-1dc88b331642
        image: pitstop/workshopmanagementapi:latest
        imagePullPolicy: IfNotPresent
        name: workshopmanagementapi
        ports:
        - containerPort: 5200
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: workshopmanagementapi
    version: v1
  name: workshopmanagementapi
  namespace: pitstop
spec:
  type: NodePort
  ports:
  - name: "http-5200"
    port: 5200
    targetPort: 5200
    nodePort: 30007
  selector:
    system: pitstop
    app: workshopmanagementapi
    version: v1
